# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [3]:
import numpy as np

# Configuration de la précision d'affichage
np.set_printoptions(precision=2, suppress=True)
print("NumPy version:", np.__version__)

NumPy version: 2.5.2


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [4]:
# VOTRE CODE ICI
numbers = np.arange(1,21)
result = numbers.reshape(4,5)
print(result)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [ ]:
# VOTRE CODE ICI
numbers = np.random.randint(0, 51, 15)
print(numbers)
result = numbers[(numbers > 25) & (numbers % 2 == 0)]
print(result)

[45 42  1 41 28  3 37 31 36 27 12 10 44 26  5]
[42 28 36 44 26]


## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [ ]:
# VOTRE CODE ICI
numbers = np.arange(1,11)
print(numbers[::-1])



[10  9  8  7  6  5  4  3  2  1]


In [27]:
numbers = np.random.randint(0, 100, 16)
numbers = numbers.reshape(4, 4)
print(numbers)
numbers = numbers[:, ::-1]
print(numbers)

[[91 71 27 72]
 [24 83 80 83]
 [ 9 41 49 23]
 [63 80  4 83]]
[[72 27 71 91]
 [83 80 83 24]
 [23 49 41  9]
 [83  4 80 63]]


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [32]:
# VOTRE CODE ICI
numbers = np.random.randint(1, 101, 15)
matrix = numbers.reshape(5,3)
print(matrix)
print('')
print('')
print(f'max of each row : {matrix.max(axis=1)}')
print(f'max of each column : {matrix.max(axis=0)}')

print(f'sum of each row : {matrix.sum(axis=1)}')
print(f'sum of each column : {matrix.sum(axis=0)}')

[[ 46  48  37]
 [ 90  55  29]
 [ 30  22  13]
 [  9  16 100]
 [ 12  55  98]]


max of each row : [ 48  90  30 100  98]
max of each column : [ 90  55 100]
sum of each row : [131 174  65 125 165]
sum of each column : [187 196 277]


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [43]:
# VOTRE CODE ICI
numbers = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
avg = np.nanmean(numbers)
numbers[np.isnan(numbers)] = avg
print(numbers)
print('')

numbers[[0, 2, 4]] = 100
print(numbers)
print('')

print(numbers[[0, 2, 4]])

[1.   2.   3.25 4.   3.25 6.  ]

[100.   2. 100.   4. 100.   6.]

[100. 100. 100.]


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [39]:
# VOTRE CODE ICI
m1 = np.random.randint(1, 50, 6).reshape(3,2)
m2 = np.random.randint(1, 50, 6).reshape(3,2)

print(m1)
print(m2)

r1 = np.hstack((m1, m2))
r2 = np.vstack((m1, m2))
print('')
r3 = np.concatenate((m1, m2), axis=1)
print(f'the co,catination test : {r3}')
# print('')
# print(r1)
# print('')
# print(r2)




[[12 35]
 [28  2]
 [25  9]]
[[10 31]
 [ 5 28]
 [43 12]]

the co,catination test : [[12 35 10 31]
 [28  2  5 28]
 [25  9 43 12]]


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [10]:
# VOTRE CODE ICI


## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.

In [11]:
# VOTRE CODE ICI


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [12]:
# VOTRE CODE ICI


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [ ]:
# VOTRE CODE ICI
numbers = np.array([1,2,3,4,5,6,7,8])
result = np.lib.stride_tricks.sliding_window_view(numbers, 3)
print(result)



[array([1, 2, 3, 4]), array([2, 3, 4, 5]), array([3, 4, 5, 6]), array([4, 5, 6, 7]), array([5, 6, 7, 8])]


In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8])
windwo = []
for i in range(len(numbers) -4 +1 ):
    windwo.append(numbers[i:i+4])
print(windwo)


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [70]:
# VOTRE CODE ICI
numbers = np.random.randint(1, 101, 48).reshape(6, 8)
print(numbers)
print(f'sorted index : {np.argsort(numbers, axis=1)}')
print('')
max_index = np.argsort(numbers, axis=1)[:, -3:]
max_index_test = np.argsort(numbers, axis=1)[:, :-3]
max_index_test = np.argsort(numbers, axis=1)[:, -3:]
print(max_index)
print('')
print(max_index_test)


[[ 71  63  65  18  50  56  80  21]
 [ 26  39  91   7  25  69  87  99]
 [ 24 100  17  18  53  78   7  92]
 [ 31  42  95  44  62  62  83  58]
 [ 77  43  95  14  61  47  15   3]
 [ 58   1  59  23  28  88  90  24]]
sorted index : [[3 7 4 5 1 2 0 6]
 [3 4 0 1 5 6 2 7]
 [6 2 3 0 4 5 7 1]
 [0 1 3 7 5 4 6 2]
 [7 3 6 1 5 4 0 2]
 [1 3 7 4 0 2 5 6]]

[[2 0 6]
 [6 2 7]
 [5 7 1]
 [4 6 2]
 [4 0 2]
 [2 5 6]]

[[2 0 6]
 [6 2 7]
 [5 7 1]
 [4 6 2]
 [4 0 2]
 [2 5 6]]
